kind: pipeline
name: build-and-test

steps:
- name: test
  image: git.agnos.is/projectmoon/gemfreely-build
  commands:
  - cargo build
  - cargo test --verbose
  - cargo deny check licenses

- name: build-release
  image: git.agnos.is/projectmoon/gemfreely-build
  when:
    ref:
    - refs/tags/v*
  commands:
  - cargo build --config .cargo/static-build.toml --release

- name: push-release
  image: plugins/gitea-release
  when:
    ref:
    - refs/tags/v*
  settings:
    api_key:
      from_secret: release_push_key
    base_url: https://git.agnos.is/
    files: target/x86_64-unknown-linux-gnu/release/gemfreely
