kind: pipeline
name: build-and-test

steps:
- name: test
  image: rust:1.76-slim
  commands:
  - rustup component add rustfmt
  - cargo install --locked cargo deny
  - cargo build
  - cargo test --verbose
  - cargo deny check licenses
