# Root options

# The graph table configures how the dependency graph is constructed and thus
# which crates the checks are performed against
[graph]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[licenses]
version = 2
unused-allowed-license = "allow"
confidence-threshold = 0.95
allow = [
      "GPL-1.0",
      "GPL-2.0",
      "GPL-3.0",
      "LGPL-2.0",
      "LGPL-2.1",
      "LGPL-3.0",
      "AGPL-3.0",
      "EUPL-1.2",
      "MIT",
      "Apache-2.0",
      "MPL-2.0",
      "ISC",
      "Unicode-DFS-2016",
      "OpenSSL",
      "BSD-3-Clause"
]

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification entry for it allows you to manually specify the
# licensing information
[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 }
]

[[licenses.clarify]]
crate = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"